[manager]
ratio = [1, 3, 4]
show_hidden = true
show_symlink = true

[plugin]
prepend_previewers = [
	{ mime = "image/*", run = "chafa" },
	{ mime = "text/csv", run = "miller_csv"},
	{ mime = "text/json", run = "miller_json"},
	{ mime = "text/jsonl", run = "miller_jsonl"},
]
