settings:
  use_slurm_when_available: True
  local_automatic_gpu_assignment: False
  mute_status: False  # mute status message
open:
  python: ".py"
server:
  cpu_default:
    p: dell_cpu
    q: cpu_qos
  default:
    p: suma_A6000
    q: big_qos
  a6000:
    p: suma_A6000
    q: big_qos
  "3090":
    p: dell_rtx3090
    q: big_qos
  "4090":
    p: suma_rtx4090
    q: big_qos
  a100:
    p: suma_a100_1
    q: a100_1_qos
